---
title: "Assignment 1: Introduction"
author: "Nadia Swit"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Salk_A03_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.


## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I took Betsy Albright's Applied Statistics course last fall. Previously I have worked as a GIS intern for a water utility where I learned about data analytics and how it is applied to geospatial processes. However, I did not utilize much analysis besides what I completed in MOOCs with Esri. I have no previous experience with Git.

2. Are there any components of the course about which you feel confident?

> Answer: I feel I have a good basic understanding of the basic components of data analysis and am familiar with the different approaches. I also have a working knowledge of R.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I am not fully confident overall of my capabilities, even though I am familiar with the techniques and have discussed them in class or reviewed them with independent learning in a working environment. However, if I was tasked to analyze something, I am not fully confident that I will know all the skills and techniques I should in order to perform the task properly. 


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/nadiaswit/Environmental_Data_Analytics_2021.git


